/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type { CommonResponseListIndustryResponse } from '../refit-api.schemas'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'


/**
 * @summary 산업군 리스트를 조회합니다.
 */
export type getIndustriesResponse200 = {
  data: CommonResponseListIndustryResponse
  status: 200
}

export type getIndustriesResponseSuccess = getIndustriesResponse200 & {
  headers: Headers
}
export type getIndustriesResponse = getIndustriesResponseSuccess

export const getGetIndustriesUrl = () => {
  return `/industry`
}

export const getIndustries = async (options?: RequestInit): Promise<getIndustriesResponse> => {
  const res = await fetch(getGetIndustriesUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getIndustriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIndustriesResponse
}

export const getGetIndustriesQueryKey = () => {
  return [`/industry`] as const
}

export const getGetIndustriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getIndustries>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndustries>>, TError, TData>>
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetIndustriesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIndustries>>> = ({ signal }) =>
    getIndustries({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getIndustries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIndustriesQueryResult = NonNullable<Awaited<ReturnType<typeof getIndustries>>>
export type GetIndustriesQueryError = unknown

export function useGetIndustries<TData = Awaited<ReturnType<typeof getIndustries>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndustries>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndustries>>,
          TError,
          Awaited<ReturnType<typeof getIndustries>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIndustries<TData = Awaited<ReturnType<typeof getIndustries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndustries>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndustries>>,
          TError,
          Awaited<ReturnType<typeof getIndustries>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIndustries<TData = Awaited<ReturnType<typeof getIndustries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndustries>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 산업군 리스트를 조회합니다.
 */

export function useGetIndustries<TData = Awaited<ReturnType<typeof getIndustries>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndustries>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetIndustriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
