/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type { HandleOAuth2CallbackParams } from '../refit-api.schemas'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'


export type getOAuth2LoginUrlResponse200 = {
  data: Blob
  status: 200
}

export type getOAuth2LoginUrlResponseSuccess = getOAuth2LoginUrlResponse200 & {
  headers: Headers
}
export type getOAuth2LoginUrlResponse = getOAuth2LoginUrlResponseSuccess

export const getGetOAuth2LoginUrlUrl = () => {
  return `/auth/login/google`
}

export const getOAuth2LoginUrl = async (options?: RequestInit): Promise<getOAuth2LoginUrlResponse> => {
  const res = await fetch(getGetOAuth2LoginUrlUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getOAuth2LoginUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOAuth2LoginUrlResponse
}

export const getGetOAuth2LoginUrlQueryKey = () => {
  return [`/auth/login/google`] as const
}

export const getGetOAuth2LoginUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getOAuth2LoginUrl>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError, TData>>
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOAuth2LoginUrlQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOAuth2LoginUrl>>> = ({ signal }) =>
    getOAuth2LoginUrl({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOAuth2LoginUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOAuth2LoginUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getOAuth2LoginUrl>>>
export type GetOAuth2LoginUrlQueryError = unknown

export function useGetOAuth2LoginUrl<TData = Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuth2LoginUrl>>,
          TError,
          Awaited<ReturnType<typeof getOAuth2LoginUrl>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOAuth2LoginUrl<TData = Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOAuth2LoginUrl>>,
          TError,
          Awaited<ReturnType<typeof getOAuth2LoginUrl>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOAuth2LoginUrl<TData = Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOAuth2LoginUrl<TData = Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOAuth2LoginUrl>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOAuth2LoginUrlQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type handleOAuth2CallbackResponse200 = {
  data: void
  status: 200
}

export type handleOAuth2CallbackResponseSuccess = handleOAuth2CallbackResponse200 & {
  headers: Headers
}
export type handleOAuth2CallbackResponse = handleOAuth2CallbackResponseSuccess

export const getHandleOAuth2CallbackUrl = (params: HandleOAuth2CallbackParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/auth/login/google/callback?${stringifiedParams}`
    : `/auth/login/google/callback`
}

export const handleOAuth2Callback = async (
  params: HandleOAuth2CallbackParams,
  options?: RequestInit,
): Promise<handleOAuth2CallbackResponse> => {
  const res = await fetch(getHandleOAuth2CallbackUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: handleOAuth2CallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleOAuth2CallbackResponse
}

export const getHandleOAuth2CallbackQueryKey = (params?: HandleOAuth2CallbackParams) => {
  return [`/auth/login/google/callback`, ...(params ? [params] : [])] as const
}

export const getHandleOAuth2CallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof handleOAuth2Callback>>,
  TError = unknown,
>(
  params: HandleOAuth2CallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof handleOAuth2Callback>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getHandleOAuth2CallbackQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof handleOAuth2Callback>>> = ({ signal }) =>
    handleOAuth2Callback(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof handleOAuth2Callback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleOAuth2CallbackQueryResult = NonNullable<Awaited<ReturnType<typeof handleOAuth2Callback>>>
export type HandleOAuth2CallbackQueryError = unknown

export function useHandleOAuth2Callback<TData = Awaited<ReturnType<typeof handleOAuth2Callback>>, TError = unknown>(
  params: HandleOAuth2CallbackParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof handleOAuth2Callback>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleOAuth2Callback>>,
          TError,
          Awaited<ReturnType<typeof handleOAuth2Callback>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleOAuth2Callback<TData = Awaited<ReturnType<typeof handleOAuth2Callback>>, TError = unknown>(
  params: HandleOAuth2CallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof handleOAuth2Callback>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleOAuth2Callback>>,
          TError,
          Awaited<ReturnType<typeof handleOAuth2Callback>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleOAuth2Callback<TData = Awaited<ReturnType<typeof handleOAuth2Callback>>, TError = unknown>(
  params: HandleOAuth2CallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof handleOAuth2Callback>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHandleOAuth2Callback<TData = Awaited<ReturnType<typeof handleOAuth2Callback>>, TError = unknown>(
  params: HandleOAuth2CallbackParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof handleOAuth2Callback>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHandleOAuth2CallbackQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
