/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, http } from 'msw'
import type {
  CommonResponseListFrequentQnaSetResponse,
  CommonResponseListPdfHighlightingDto,
  CommonResponseVoid,
} from '../refit-api.schemas'
import type { RequestHandlerOptions } from 'msw'


export const getUpdateQnaSetResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getGetPdfHighlightingsResponseMock = (
  overrideResponse: Partial<CommonResponseListPdfHighlightingDto> = {},
): CommonResponseListPdfHighlightingDto => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      pdfHighlightingId: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
      highlightingText: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      rects: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
          x: faker.helpers.arrayElement([
            faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
            undefined,
          ]),
          y: faker.helpers.arrayElement([
            faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
            undefined,
          ]),
          width: faker.helpers.arrayElement([
            faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
            undefined,
          ]),
          height: faker.helpers.arrayElement([
            faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
            undefined,
          ]),
          pageNumber: faker.helpers.arrayElement([faker.number.int({ min: undefined, max: undefined }), undefined]),
        })),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUpdatePdfHighlightingResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getUnmarkDifficultQuestionResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getMarkDifficultQuestionResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getGetFrequentQuestionsResponseMock = (
  overrideResponse: Partial<CommonResponseListFrequentQnaSetResponse> = {},
): CommonResponseListFrequentQnaSetResponse => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
      question: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
})

export const getUpdateQnaSetMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/qna-set/:qnaSetId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdateQnaSetResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getGetPdfHighlightingsMockHandler = (
  overrideResponse?:
    | CommonResponseListPdfHighlightingDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CommonResponseListPdfHighlightingDto> | CommonResponseListPdfHighlightingDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/qna-set/:qnaSetId/pdf-highlightings',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetPdfHighlightingsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getUpdatePdfHighlightingMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/qna-set/:qnaSetId/pdf-highlightings',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUpdatePdfHighlightingResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getUnmarkDifficultQuestionMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    '*/qna-set/:qnaSetId/difficult/unmark',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUnmarkDifficultQuestionResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getMarkDifficultQuestionMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    '*/qna-set/:qnaSetId/difficult/mark',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getMarkDifficultQuestionResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getGetFrequentQuestionsMockHandler = (
  overrideResponse?:
    | CommonResponseListFrequentQnaSetResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CommonResponseListFrequentQnaSetResponse> | CommonResponseListFrequentQnaSetResponse),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/qna-set/frequent',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetFrequentQuestionsResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getQnaSetApiMock = () => [
  getUpdateQnaSetMockHandler(),
  getGetPdfHighlightingsMockHandler(),
  getUpdatePdfHighlightingMockHandler(),
  getUnmarkDifficultQuestionMockHandler(),
  getMarkDifficultQuestionMockHandler(),
  getGetFrequentQuestionsMockHandler(),
]
