import type { LabelValueType } from '@/types/global'

export const INTERVIEW_TYPE_LABEL = {
  first: '1차 면접',
  second: '2차 면접',
  third: '3차 면접',
  personality: '인성 면접',
  technical: '기술 면접',
  executive: '임원 면접',
  culture: '컬쳐핏 면접',
  coffee: '커피챗',
  mock: '모의 면접',
} as const

export const INTERVIEW_TYPE_OPTIONS: LabelValueType[] = Object.entries(INTERVIEW_TYPE_LABEL).map(([value, label]) => ({
  value,
  label,
}))

export const INDUSTRIES = [
  { id: 1, label: '서비스업' },
  { id: 2, label: '금융·은행업' },
  { id: 3, label: 'IT·정보통신업' },
  { id: 4, label: '판매·유통업' },
  { id: 5, label: '제조' },
  { id: 6, label: '생산' },
  { id: 7, label: '화학업' },
  { id: 8, label: '교육업' },
  { id: 9, label: '건설업' },
  { id: 10, label: '의료·제약업' },
  { id: 11, label: '미디어·광고업' },
  { id: 12, label: '문화·예술·디자인업' },
  { id: 13, label: '기관·협회' },
]

export const JOB_CATEGORIES = [
  { id: 1, label: '기획' },
  { id: 2, label: '전략' },
  { id: 3, label: '법무' },
  { id: 4, label: '사무' },
  { id: 5, label: '총무' },
  { id: 6, label: '인사·HR' },
  { id: 7, label: '회계' },
  { id: 8, label: '세무' },
  { id: 9, label: '마케팅' },
  { id: 10, label: '광고' },
  { id: 11, label: 'MD' },
  { id: 12, label: 'AI' },
  { id: 13, label: '개발' },
  { id: 14, label: '데이터' },
  { id: 15, label: '디자인' },
  { id: 16, label: '물류' },
  { id: 17, label: '무역' },
  { id: 18, label: '운전' },
  { id: 19, label: '운송' },
  { id: 20, label: '배송' },
  { id: 21, label: '영업' },
  { id: 22, label: '고객상담' },
  { id: 23, label: 'TM' },
  { id: 24, label: '금융' },
  { id: 25, label: '보험' },
  { id: 26, label: '식·음료' },
  { id: 27, label: '고객서비스' },
  { id: 28, label: '리테일' },
  { id: 29, label: '엔지니어링' },
  { id: 30, label: '설계' },
  { id: 31, label: '제조·생산' },
  { id: 32, label: '교육' },
  { id: 33, label: '건축' },
  { id: 34, label: '시설' },
  { id: 35, label: '의료·바이오' },
  { id: 36, label: '미디어·문화' },
  { id: 37, label: '스포츠' },
  { id: 38, label: '공공·복지' },
]
