/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  CommonResponsePageInterviewDto,
  CommonResponsePageInterviewSimpleDto,
  GetMyInterviewDraftsParams,
  GetMyInterviewsParams,
  InterviewSearchRequest,
  SearchInterviewsParams,
} from '../refit-api.schemas'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'


/**
 * @summary 내가 복기 완료한 면접을 검색합니다.
 */
export type searchInterviewsResponse200 = {
  data: CommonResponsePageInterviewDto
  status: 200
}

export type searchInterviewsResponseSuccess = searchInterviewsResponse200 & {
  headers: Headers
}
export type searchInterviewsResponse = searchInterviewsResponseSuccess

export const getSearchInterviewsUrl = (params: SearchInterviewsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/interview/my/search?${stringifiedParams}` : `/interview/my/search`
}

export const searchInterviews = async (
  interviewSearchRequest: InterviewSearchRequest,
  params: SearchInterviewsParams,
  options?: RequestInit,
): Promise<searchInterviewsResponse> => {
  const res = await fetch(getSearchInterviewsUrl(params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(interviewSearchRequest),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: searchInterviewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchInterviewsResponse
}

export const getSearchInterviewsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof searchInterviews>>,
    TError,
    { data: InterviewSearchRequest; params: SearchInterviewsParams },
    TContext
  >
  fetch?: RequestInit
}): UseMutationOptions<
  Awaited<ReturnType<typeof searchInterviews>>,
  TError,
  { data: InterviewSearchRequest; params: SearchInterviewsParams },
  TContext
> => {
  const mutationKey = ['searchInterviews']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof searchInterviews>>,
    { data: InterviewSearchRequest; params: SearchInterviewsParams }
  > = (props) => {
    const { data, params } = props ?? {}

    return searchInterviews(data, params, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SearchInterviewsMutationResult = NonNullable<Awaited<ReturnType<typeof searchInterviews>>>
export type SearchInterviewsMutationBody = InterviewSearchRequest
export type SearchInterviewsMutationError = unknown

/**
 * @summary 내가 복기 완료한 면접을 검색합니다.
 */
export const useSearchInterviews = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof searchInterviews>>,
      TError,
      { data: InterviewSearchRequest; params: SearchInterviewsParams },
      TContext
    >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof searchInterviews>>,
  TError,
  { data: InterviewSearchRequest; params: SearchInterviewsParams },
  TContext
> => {
  return useMutation(getSearchInterviewsMutationOptions(options), queryClient)
}
/**
 * @deprecated
 * @summary 내가 복기 완료한 면접 정보를 조회합니다. (검색 API 와 통합 예정입니다)
 */
export type getMyInterviewsResponse200 = {
  data: CommonResponsePageInterviewSimpleDto
  status: 200
}

export type getMyInterviewsResponseSuccess = getMyInterviewsResponse200 & {
  headers: Headers
}
export type getMyInterviewsResponse = getMyInterviewsResponseSuccess

export const getGetMyInterviewsUrl = (params: GetMyInterviewsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/interview/my?${stringifiedParams}` : `/interview/my`
}

export const getMyInterviews = async (
  params: GetMyInterviewsParams,
  options?: RequestInit,
): Promise<getMyInterviewsResponse> => {
  const res = await fetch(getGetMyInterviewsUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getMyInterviewsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyInterviewsResponse
}

export const getGetMyInterviewsQueryKey = (params?: GetMyInterviewsParams) => {
  return [`/interview/my`, ...(params ? [params] : [])] as const
}

export const getGetMyInterviewsQueryOptions = <TData = Awaited<ReturnType<typeof getMyInterviews>>, TError = unknown>(
  params: GetMyInterviewsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviews>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMyInterviewsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInterviews>>> = ({ signal }) =>
    getMyInterviews(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInterviews>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInterviewsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInterviews>>>
export type GetMyInterviewsQueryError = unknown

export function useGetMyInterviews<TData = Awaited<ReturnType<typeof getMyInterviews>>, TError = unknown>(
  params: GetMyInterviewsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviews>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInterviews>>,
          TError,
          Awaited<ReturnType<typeof getMyInterviews>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInterviews<TData = Awaited<ReturnType<typeof getMyInterviews>>, TError = unknown>(
  params: GetMyInterviewsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviews>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInterviews>>,
          TError,
          Awaited<ReturnType<typeof getMyInterviews>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInterviews<TData = Awaited<ReturnType<typeof getMyInterviews>>, TError = unknown>(
  params: GetMyInterviewsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviews>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @deprecated
 * @summary 내가 복기 완료한 면접 정보를 조회합니다. (검색 API 와 통합 예정입니다)
 */

export function useGetMyInterviews<TData = Awaited<ReturnType<typeof getMyInterviews>>, TError = unknown>(
  params: GetMyInterviewsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviews>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyInterviewsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * interviewReviewStatus 에는 LOG_DRAFT (기록 중), SELF_REVIEW_DRAFT (회고 중) 값만 들어갈 수 있습니다.
이외의 값에 대해서는 400 에러를 응답합니다.

 * @summary 내가 작성중인 (임시저장) 복기 데이터를 조회합니다.
 */
export type getMyInterviewDraftsResponse200 = {
  data: CommonResponsePageInterviewSimpleDto
  status: 200
}

export type getMyInterviewDraftsResponseSuccess = getMyInterviewDraftsResponse200 & {
  headers: Headers
}
export type getMyInterviewDraftsResponse = getMyInterviewDraftsResponseSuccess

export const getGetMyInterviewDraftsUrl = (params: GetMyInterviewDraftsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/interview/my/draft?${stringifiedParams}` : `/interview/my/draft`
}

export const getMyInterviewDrafts = async (
  params: GetMyInterviewDraftsParams,
  options?: RequestInit,
): Promise<getMyInterviewDraftsResponse> => {
  const res = await fetch(getGetMyInterviewDraftsUrl(params), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getMyInterviewDraftsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMyInterviewDraftsResponse
}

export const getGetMyInterviewDraftsQueryKey = (params?: GetMyInterviewDraftsParams) => {
  return [`/interview/my/draft`, ...(params ? [params] : [])] as const
}

export const getGetMyInterviewDraftsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyInterviewDrafts>>,
  TError = unknown,
>(
  params: GetMyInterviewDraftsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError, TData>>
    fetch?: RequestInit
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetMyInterviewDraftsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyInterviewDrafts>>> = ({ signal }) =>
    getMyInterviewDrafts(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyInterviewDrafts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyInterviewDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyInterviewDrafts>>>
export type GetMyInterviewDraftsQueryError = unknown

export function useGetMyInterviewDrafts<TData = Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError = unknown>(
  params: GetMyInterviewDraftsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInterviewDrafts>>,
          TError,
          Awaited<ReturnType<typeof getMyInterviewDrafts>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInterviewDrafts<TData = Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError = unknown>(
  params: GetMyInterviewDraftsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyInterviewDrafts>>,
          TError,
          Awaited<ReturnType<typeof getMyInterviewDrafts>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyInterviewDrafts<TData = Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError = unknown>(
  params: GetMyInterviewDraftsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내가 작성중인 (임시저장) 복기 데이터를 조회합니다.
 */

export function useGetMyInterviewDrafts<TData = Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError = unknown>(
  params: GetMyInterviewDraftsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyInterviewDrafts>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyInterviewDraftsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
