/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

export type getAllJobCategoriesResponse200 = {
  data: Blob
  status: 200
}

export type getAllJobCategoriesResponseSuccess = getAllJobCategoriesResponse200 & {
  headers: Headers
}
export type getAllJobCategoriesResponse = getAllJobCategoriesResponseSuccess

export const getGetAllJobCategoriesUrl = () => {
  return `/job-category`
}

export const getAllJobCategories = async (options?: RequestInit): Promise<getAllJobCategoriesResponse> => {
  const res = await fetch(getGetAllJobCategoriesUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAllJobCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllJobCategoriesResponse
}

export const getGetAllJobCategoriesQueryKey = () => {
  return [`/job-category`] as const
}

export const getGetAllJobCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllJobCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJobCategories>>, TError, TData>>
  fetch?: RequestInit
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllJobCategoriesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllJobCategories>>> = ({ signal }) =>
    getAllJobCategories({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllJobCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllJobCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllJobCategories>>>
export type GetAllJobCategoriesQueryError = unknown

export function useGetAllJobCategories<TData = Awaited<ReturnType<typeof getAllJobCategories>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJobCategories>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllJobCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllJobCategories>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllJobCategories<TData = Awaited<ReturnType<typeof getAllJobCategories>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJobCategories>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllJobCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllJobCategories>>
        >,
        'initialData'
      >
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllJobCategories<TData = Awaited<ReturnType<typeof getAllJobCategories>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJobCategories>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllJobCategories<TData = Awaited<ReturnType<typeof getAllJobCategories>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllJobCategories>>, TError, TData>>
    fetch?: RequestInit
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllJobCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}
