/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, http } from 'msw'
import type { CommonResponseTokenPairDto, CommonResponseVoid } from '../refit-api.schemas'
import type { RequestHandlerOptions } from 'msw'


export const getGetTokenResponseMock = (
  overrideResponse: Partial<CommonResponseTokenPairDto> = {},
): CommonResponseTokenPairDto => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([
    {
      accessToken: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      refreshToken: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
})

export const getGetGuestTokenResponseMock = (
  overrideResponse: Partial<CommonResponseTokenPairDto> = {},
): CommonResponseTokenPairDto => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([
    {
      accessToken: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
      refreshToken: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
})

export const getDeleteUserByEmailResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getDeleteUserByIdResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getDeleteTokenCookiesResponseMock = (
  overrideResponse: Partial<CommonResponseVoid> = {},
): CommonResponseVoid => ({
  isSuccess: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  result: faker.helpers.arrayElement([{}, undefined]),
  ...overrideResponse,
})

export const getGetTokenMockHandler = (
  overrideResponse?:
    | CommonResponseTokenPairDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CommonResponseTokenPairDto> | CommonResponseTokenPairDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/test/auth/token',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetTokenResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getGetGuestTokenMockHandler = (
  overrideResponse?:
    | CommonResponseTokenPairDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CommonResponseTokenPairDto> | CommonResponseTokenPairDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/test/auth/token/guest',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetGuestTokenResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getDeleteUserByEmailMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/test/user',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteUserByEmailResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getDeleteUserByIdMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/test/user/:userId',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteUserByIdResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}

export const getDeleteTokenCookiesMockHandler = (
  overrideResponse?:
    | CommonResponseVoid
    | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<CommonResponseVoid> | CommonResponseVoid),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/test/auth/token/cookies',
    async (info) => {
      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getDeleteTokenCookiesResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      )
    },
    options,
  )
}
export const getTestAuthUserApiMock = () => [
  getGetTokenMockHandler(),
  getGetGuestTokenMockHandler(),
  getDeleteUserByEmailMockHandler(),
  getDeleteUserByIdMockHandler(),
  getDeleteTokenCookiesMockHandler(),
]
